### PR TITLE
Fixes a problem with URLs containing a ';' character (Issue #14). Now…

### PR DESCRIPTION
**Pull request by dlarsson**
… properly pulls out the URL before the ending '>' before splitting on the ';' delimiter between the URL and the attributes.

### CODE REVIEW

**Comment by thlorenz** [comment]
Please don't change any existing tests and omit all the white space changes.
It's hard to look at the diff.

In summary please only add a test and the code change, no more.
Everything still needs to work as before for existing cases which is why all existing tests need to stay untouched.

Thanks.

**Comment by dlarsson** [comment]
I'll fix the white space changes, I guess my editor removed spurious white
space at end of lines.

Regarding the change tests, they specify faulty Link values, the URLs are
missing the final ">" character. I assumed this was a mistake, and my
change will not parse such links. Is this a feature that the old parser
handled those?

2017-04-09 15:17 GMT+02:00 Thorsten Lorenz <notifications@github.com>:

**Comment by thlorenz** [comment]
> he URLs are missing the final ">" character

Ah that makes sense afaik they'd have to have that character.
So I think it's ok if you fix those.

I'll make sure to release a new major in order to not break anyone who may be depending on that bug.

**Comment by dlarsson** [comment]
On vacation trip, and won't have access to my laptop for a few days, but I
will push the updated patch at end of the week

Den 10 apr. 2017 6:22 em skrev "Thorsten Lorenz" <notifications@github.com>:

**Pull request closed without merging**
