### PR TITLE
Fix parsing rels without quotes

### PR DESCRIPTION
**Pull request by jarofghosts**
There is actually nothing in [the spec](https://tools.ietf.org/html/rfc5988#page-7) that requires quotes around the rel type. This fixes that assumption and adds a test around it.

### CODE REVIEW

**Comment by thlorenz** [comment]
LGTM, please merge to master. I'll publish as a minor as this more strict regex may break some rare cases.

**Comment by thlorenz** [comment]
Should have said forward merge (I hate merge commits).
So please rebase master so that's gone.
_wishes their wasn't a merge button on github_

**Comment by jarofghosts** [comment]
sorry! will do

**Comment by jarofghosts** [comment]
i should've asked, i actually feel the same way but some people prefer The Big Green Button

**Comment by thlorenz** [comment]
Thanks and no problem at all :)

Published as 0.3

**Pull request merged**
