### PR TITLE
Drop dependencies

### LINKED ISSUE #23: Replace `url` and `querystring` dependencies with `URL` and `URLSearchParams`
As the title suggests, these new APIs are available globally in the recent Node releases.

### PR DESCRIPTION
**Pull request by fregante**
- Fixes https://github.com/thlorenz/parse-link-header/issues/23

Is this what you meant?

Side note: This drops support for IE as well

- https://developer.mozilla.org/en-US/docs/Web/API/URL
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/fromEntries

### CODE REVIEW

**Comment by thlorenz** [comment]
Thanks for the PR, but this is beyond what we agreed to in the issue.
`Object.assign` is fine, but loosing compat below v10 just for some extra syntactic sugar isn't that great.

Please modify this to minimize impact and just solve what's in the issue.

**Comment by fregante** [comment]
I don't know what we agreed to. My last message in that issue is about `URL`, not `Object.assign`, that's why I asked what you meant here

**Comment by thlorenz** [comment]
OK could be we misunderstood each other, but please adapt this to only change what's needed to replace the two obsolete module and leave out the _modernizing_ JavaScript things.
Thanks for being patient 😸

**Comment by fregante** [comment]
I still don’t understand what your idea is here. The only extra thing I changed was fromEntries, which is unrelated to the extra modules. Either I remove the dependencies or I don’t.

**Comment by martijnpieters** [comment]
@thlorenz Could you review this again, and possibly merge and release afterwards? Thanks!

**Comment by thlorenz** [comment]
This looks good now. Please rebase on master and I'll merge and publish as new minor (just upped the major version, so should be fine).

**Comment by martijnpieters** [comment]
@thlorenz 😇

**Comment by gilbarbara** [comment]
@fregante @thlorenz 

The URL constructor will break with relative URLs. You could set a fake `base` parameter in that case

**Comment by alanshaw** [comment]
Incase anyone needs it, I merged this PR (to resolve https://github.com/thlorenz/parse-link-header/issues/23), removed Node.js globals (to resolve https://github.com/thlorenz/parse-link-header/issues/28) and converted to ESM in this fork: https://github.com/web3-storage/parse-link-header

**Comment by lambdakris** [comment]
Hey all, I stumbled with the node deps issue as well and wanted to chime in on the utility of this PR. Is there anything else pending about this or have all the concerns been addressed?

**Comment by fregante** [comment]
Does anything need to be done here? It will turn 1-year old in a couple of months 😃

**Comment by martijnpieters** [comment]
@fregante thanks for your effort in improving this library, too bad the maintainer doesn't like a proper implementation

**Pull request closed without merging**
